### ISSUE TITLE
验证码不显示

### ISSUE THREAD

**Issue by liuts** [arklnk/ark-admin-vuenext#36]
git clone 拉下来以后，执行  pnpm i     然后  pnpm dev 

报错信息：
![图片](https://user-images.githubusercontent.com/8000832/213076690-1fec862e-32cc-4fee-b6b3-1aa4708d1b94.png)

页面报错信息：

![图片](https://user-images.githubusercontent.com/8000832/213076741-25288bcc-c71e-4b55-95ca-a5b0576c5be6.png)

![图片](https://user-images.githubusercontent.com/8000832/213076973-f9488e39-947a-4f78-a239-4fb771f9353a.png)

**Comment by hackycy** [comment]
需要go版后端或者nest版后端配合的，单跑前端是无法体验完整功能的
